name: "Publish (server)"

on:
  push:
    branches:
      - feat/register-allow-list
  workflow_dispatch:

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feat/register-allow-list
          fetch-depth: 0

      - name: Get commit SHA
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: server/Dockerfile
          directory: server
          image: server
          registry: ghcr.io
          enableBuildKit: true
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          buildArgs: GIT_COMMIT=${{ steps.sha.outputs.sha }}
          tags: ${{ steps.sha.outputs.sha }}, latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}